services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

volumes:
    wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/dcruz-na/data/wordpress
      o: bind
